eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
server:
  port: 8021
spring:
  application:
    name: service-feign

# 打开hystrix功能（feign的熔断器默认是关的）
feign:
  hystrix:
    enabled: true